// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[slug].tsx";
import * as $1 from "./routes/about.tsx";
import * as $2 from "./routes/blog/[slug].tsx";
import * as $3 from "./routes/blog/index.tsx";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/projects.tsx";

const manifest = {
  routes: {
    "./routes/[slug].tsx": $0,
    "./routes/about.tsx": $1,
    "./routes/blog/[slug].tsx": $2,
    "./routes/blog/index.tsx": $3,
    "./routes/index.tsx": $4,
    "./routes/projects.tsx": $5,
  },
  islands: {},
  baseUrl: import.meta.url,
  config,
};

export default manifest;
